LLM_TIMEOUT_SECONDS = 120
LLM_ENDPOINT = "/chat/completions"
LLM_STOP_SEQUENCE = ["<end_code>", "</tool_calls>"]


MBPP_INPUT_MAX_TOKEN = 6000
MBPP_OUTPUT_MAX_TOKEN = 1500

SWE_INPUT_MAX_TOKEN = 300000
SWE_OUTPUT_MAX_TOKEN = 10000
