import builtins

SAFE = [
    # Types & conversions
    "bool",
    "int",
    "float",
    "complex",
    "str",
    "bytes",
    "bytearray",
    "list",
    "tuple",
    "dict",
    "set",
    "frozenset",
    # Iteration & sequences
    "len",
    "range",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "reversed",
    "iter",
    "next",
    "slice",
    "all",
    "any",
    "sum",
    "min",
    "max",
    "abs",
    "round",
    "pow",
    "divmod",
    "bin",
    "oct",
    "hex",
    "chr",
    "ord",
    "ascii",
    "format",
    "repr",
    "hash",
    "isinstance",
    "issubclass",
    "type",
    "callable",
    # Namespace: lists the names in scope, including the injected tools.
    "dir",
    "print",
    "BaseException",
    "Exception",
    "ArithmeticError",
    "ZeroDivisionError",
    "OverflowError",
    "ValueError",
    "TypeError",
    "KeyError",
    "IndexError",
    "AttributeError",
    "NameError",
    "RuntimeError",
    "StopIteration",
    "StopAsyncIteration",
    "AssertionError",
    "NotImplementedError",
    "LookupError",
    "FloatingPointError",
    # Legitimate code catches these (e.g. `try: import x except
    # ImportError`); they are exception classes, not capabilities.
    "ImportError",
    "ModuleNotFoundError",
    "MemoryError",
    "RecursionError",
    "OSError",
    "PermissionError",
    "FileNotFoundError",
    "IsADirectoryError",
    "TimeoutError",
    "UnicodeError",
    "UnicodeDecodeError",
    "UnicodeEncodeError",
    "True",
    "False",
    "None",
    "NotImplemented",
    "Ellipsis",
]


def safe_builtins() -> dict:
    d = {}
    for name in SAFE:
        if hasattr(builtins, name):
            d[name] = getattr(builtins, name)
    return d
