import builtins

SAFE = [
    "bool",
    "int",
    "float",
    "complex",
    "str",
    "bytes",
    "bytearray",
    "list",
    "tuple",
    "dict",
    "set",
    "frozenset",
    "len",
    "range",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "reversed",
    "iter",
    "next",
    "slice",
    "all",
    "any",
    "sum",
    "min",
    "max",
    "abs",
    "round",
    "pow",
    "divmod",
    "bin",
    "oct",
    "hex",
    "chr",
    "ord",
    "ascii",
    "format",
    "repr",
    "hash",
    "isinstance",
    "issubclass",
    "type",
    "callable",
    "dir",
    "print",
    "BaseException",
    "Exception",
    "ArithmeticError",
    "ZeroDivisionError",
    "OverflowError",
    "ValueError",
    "TypeError",
    "KeyError",
    "IndexError",
    "AttributeError",
    "NameError",
    "RuntimeError",
    "StopIteration",
    "StopAsyncIteration",
    "AssertionError",
    "NotImplementedError",
    "LookupError",
    "FloatingPointError",
    "ImportError",
    "ModuleNotFoundError",
    "MemoryError",
    "RecursionError",
    "OSError",
    "PermissionError",
    "FileNotFoundError",
    "IsADirectoryError",
    "TimeoutError",
    "UnicodeError",
    "UnicodeDecodeError",
    "UnicodeEncodeError",
    "True",
    "False",
    "None",
    "NotImplemented",
    "Ellipsis",
]


def safe_builtins() -> dict:
    d = {}
    for name in SAFE:
        if hasattr(builtins, name):
            d[name] = getattr(builtins, name)
    return d
